[project]
name = "rare-generations"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.4.1",
    "fire>=0.7.1",
    "huggingface-hub[cli]>=0.36.0",
    "ipython>=9.8.0",
    "jaxtyping>=0.3.3",
    "joblib>=1.5.2",
    "litellm>=1.80.9",
    "matplotlib>=3.10.7",
    "nest-asyncio>=1.6.0",
    "pandas>=2.3.3",
    "peft>=0.18.0",
    "together>=1.5.31",
    "transformers",
    "vllm==0.10.2",
    "zstandard>=0.25.0",
]

[tool.uv.sources]
transformers = { git = "https://github.com/rangell/transformers", branch = "cache_fix" }

